<?php

namespace App\Actions;

use Illuminate\Support\Facades\Gate;
use LaravelViews\Actions\Action;
use LaravelViews\Actions\Confirmable;
use LaravelViews\Views\View;

class ActivateOrDeactiveAction extends Action
{
    use Confirmable;

    /**
     * Any title you want to be displayed
     * @var String
     * */
    public $title = "فعال/غیرفعال";

    /**
     * This should be a valid Feather icon string
     * @var String
     */
    public $icon = "check";


    public function __construct(public $title_text,public $allows)
    {
        parent::__construct();
    }

    /**
     * Execute the action when the user clicked on the button
     *
     * @param $model Model object of the list where the user has clicked
     * @param $view Current view where the action was executed from
     */
    public function handle($model, View $view)
    {
        if (!is_null($this->allows) && Gate::allows($this->allows,$model)){
            $model->is_active = !$model->is_active;
            $model->save();
            $acOrDe = (!$model->is_active) ? "غیر فعال" : "فعال";
            $this->success("$this->title_text مورد نظر $acOrDe شد .");
        }else{
            $this->error('شما دسترسی این کار را ندارید!');
        }
    }
    public function renderIf($item, View $view)
    {
        if ($item->is_active) {
            $this->icon = 'check';
        }else{
            $this->icon = 'x';
        }
        return parent::renderIf($item, $view); // TODO: Change the autogenerated stub
    }

    public function getConfirmationMessage($item = null): string
    {
        $acOrDe = ($item->is_active) ? "غیر فعال" : "فعال";
        return "آیا از ".$acOrDe." کردن ".$item->title." اطمینان دارید ؟ ";
    }

}
