<?php

namespace App\Actions;

use LaravelViews\Actions\Action;
use LaravelViews\Actions\Confirmable;
use LaravelViews\Views\View;

class ActivateOrDeactiveAction extends Action
{
    use Confirmable;

    /**
     * Any title you want to be displayed
     * @var String
     * */
    public $title = "فعال/غیرفعال";

    /**
     * This should be a valid Feather icon string
     * @var String
     */
    public $icon = "check";

    /**
     * Execute the action when the user clicked on the button
     *
     * @param $model Model object of the list where the user has clicked
     * @param $view Current view where the action was executed from
     */
    public function handle($model, View $view)
    {
        $model->is_active = !$model->is_active;
        $model->save();
    }
    public function renderIf($item, View $view)
    {
        if (!$item->is_active) $this->icon = 'x';
        return parent::renderIf($item, $view); // TODO: Change the autogenerated stub
    }

    public function getConfirmationMessage($item = null): string
    {
        $acOrDe = ($item->is_active) ? "غیر فعال" : "فعال";
        return "آیا از ".$acOrDe." کردن ".$item->shortname." اطمینان دارید ؟ ";
    }
}
